### ISSUE TITLE
Running issue on the sever

### ISSUE THREAD

**Issue by Luca-Pecalli-99** [MIDIfactory/AlphaFastPPi#3]
Hello,
I have tried to use your tool to predict the protein protein interaction between 2 protein databases I have.
I have installed the AlphaFastPPi conda environment and also downloaded the alpha fold database.
During the installation of the conda enviroment I encountered 2 problems:
1) the cuda-toolkit==11 is no longer available, so I installed the latest version,
2) during the installation of the alpha-pulldown v1.0.4 the server give me back this message: 
_"ERROR: pip's dependency resolver does not currently take into account all the packages that are installed. This behaviour is the source of the following dependency conflicts. 
flax 0.9.0 requires jax>=0.4.27, but you have jax 0.4.23 which is incompatible.
optax 0.2.3 requires jax>=0.4.27, but you have jax 0.4.23 which is incompatible.
optax 0.2.3 requires jaxlib>=0.4.27, but you have jaxlib 0.4.23+cuda11.cudnn86 which is incompatible.
orbax-checkpoint 0.6.3 requires jax>=0.4.26, but you have jax 0.4.23 which is incompatible."_
But then it succesfully finish the installation.

Then, when I try to run the program following the instructions on gut-hub the system gives back this string:
" warnings.warn(
2024-09-16 17:11:36.976751: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:485] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2024-09-16 17:11:36.993838: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:8454] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2024-09-16 17:11:36.999105: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1452] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2024-09-16 17:11:38.057902: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT
I0916 17:11:42.749261 140357684012864 templates.py:857] Using precomputed obsolete pdbs /scicore/home/ebertd/pecall0000/AlphaFast/alphafold_db/pdb_mmcif/obsolete.dat.
I0916 17:11:43.122094 140357684012864 create_individual_features.py:191] running mmseq now
I0916 17:11:43.122306 140357684012864 objects.py:189] You chose to calculate MSA with mmseq2.
Please also cite: Mirdita M, Schütze K, Moriwaki Y, Heo L, Ovchinnikov S and Steinegger M. ColabFold: Making protein folding accessible to all. Nature Methods (2022) doi: 10.1038/s41592-022-01488-1
I0916 17:11:43.122743 140357684012864 objects.py:198] looking for possible precomputed a3m at /scicore/home/ebertd/pecall0000/AlphaFast/Pulldown_Results/DLEKIAJK_01313_PCL06_H1.a3m
I0916 17:11:43.122864 140357684012864 objects.py:200] input is /scicore/home/ebertd/pecall0000/AlphaFast/Pulldown_Results/DLEKIAJK_01313_PCL06_H1.a3m
COMPLETE: 100%|████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████████| 150/150 [elapsed: 00:01 remaining: 00:00]
I0916 17:11:45.596593 140357684012864 objects.py:242] will search for templates in local template database
I0916 17:11:45.598891 140357684012864 hmmbuild.py:121] Launching subprocess [None, '--amino', '/scratch/tmp7jqtqwra/output.hmm', '/scratch/tmp7jqtqwra/query.msa']

Traceback (most recent call last):
  File "/scicore/home/ebertd/pecall0000/miniconda3/envs/AlphaFastPPi/bin/create_individual_features.py", line 252, in <module>
    app.run(main)
  File "/scicore/home/ebertd/pecall0000/miniconda3/envs/AlphaFastPPi/lib/python3.10/site-packages/absl/app.py", line 308, in run
    _run_main(main, args)
  File "/scicore/home/ebertd/pecall0000/miniconda3/envs/AlphaFastPPi/lib/python3.10/site-packages/absl/app.py", line 254, in _run_main
    sys.exit(main(argv))
  File "/scicore/home/ebertd/pecall0000/miniconda3/envs/AlphaFastPPi/bin/create_individual_features.py", line 244, in main
    create_and_save_monomer_objects(curr_monomer, pipeline,
  File "/scicore/home/ebertd/pecall0000/miniconda3/envs/AlphaFastPPi/bin/create_individual_features.py", line 192, in create_and_save_monomer_objects
    m.make_mmseq_features(DEFAULT_API_SERVER=DEFAULT_API_SERVER,
  File "/scicore/home/ebertd/pecall0000/miniconda3/envs/AlphaFastPPi/lib/python3.10/site-packages/alphapulldown/objects.py", line 244, in make_mmseq_features
    template_features = self.mk_template(a3m_lines[0],
  File "/scicore/home/ebertd/pecall0000/miniconda3/envs/AlphaFastPPi/lib/python3.10/site-packages/alphapulldown/objects.py", line 172, in mk_template
    hmm_profile = hmm_build_runner.build_profile_from_a3m(a3m_lines)
  File "/scicore/home/ebertd/pecall0000/miniconda3/envs/AlphaFastPPi/lib/python3.10/site-packages/alphafold/data/tools/hmmbuild.py", line 80, in build_profile_from_a3m
    return self._build_profile(msa, model_construction='fast')
  File "/scicore/home/ebertd/pecall0000/miniconda3/envs/AlphaFastPPi/lib/python3.10/site-packages/alphafold/data/tools/hmmbuild.py", line 122, in _build_profile
    process = subprocess.Popen(cmd, stdout=subprocess.PIPE,
  File "/scicore/home/ebertd/pecall0000/miniconda3/envs/AlphaFastPPi/lib/python3.10/subprocess.py", line 966, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/scicore/home/ebertd/pecall0000/miniconda3/envs/AlphaFastPPi/lib/python3.10/subprocess.py", line 1717, in _execute_child
    and os.path.dirname(executable)
  File "/scicore/home/ebertd/pecall0000/miniconda3/envs/AlphaFastPPi/lib/python3.10/posixpath.py", line 152, in dirname
    p = os.fspath(p)
TypeError: expected str, bytes or os.PathLike object, not NoneType
" 
I have tried to update the packages, but it doesn't change and I don't know if it is a problem with the server I am running the program on and if I should move to a single computer or if it is something else.

Could you please help me?

Thank you,
Luca Pecalli

**Comment by raw937** [comment]
I am having the same issues. Any thoughts on this?
